미션 이미지 업로드 API
alloon-project/photi-server pull request #56
Opened 2024-05-15 03:01 UTC by Koojiny

## 📋 이슈 번호
- close #26 
  </br>

## 🛠 구현 사항
- 미션 이미지 업로드 API
  </br>

## 📚 기타
- 
  </br>

2024-05-15 12:11 UTC, nogamsung requested changes

2024-05-15 12:11 UTC, nogamsung commented on src/main/kotlin/com/alloon/alloonserver/api/service/mission/MissionService.kt
> +     * @throws MISSION_NOT_FOUND 404
Mission 조회를 하지 않기 때문에 이부분은 빼주세요!~

2024-05-15 12:11 UTC, nogamsung commented on src/main/kotlin/com/alloon/alloonserver/api/service/mission/MissionService.kt
> +     * @throws MISSION_NOT_FOUND 404
MISSION_NOT_FOUND만 빼주시면돼요!

2024-05-15 12:16 UTC, nogamsung commented on src/test/kotlin/com/alloon/alloonserver/api/service/mission/MissionServiceTest.kt
> +        assertThat(response).isInstanceOf(String::class.java)
assertThat이 한개 이상이면 assertAll로 감싸주면 되는데, `uploadMissionImage()`가 String만 반환하기 때문에 `assertThat(response).isInstanceOf(String::class.java)`은 빼도될거 같아요!

2024-05-16 00:27 UTC, Koojiny commented on src/main/kotlin/com/alloon/alloonserver/api/service/mission/MissionService.kt
> +     * @throws MISSION_NOT_FOUND 404
안 그래도 고민하고 있었는데 감사합니다~

2024-05-16 11:19 UTC, Koojiny commented on src/test/kotlin/com/alloon/alloonserver/api/service/mission/MissionServiceTest.kt
> +        assertThat(response).isInstanceOf(String::class.java)
수정 완료했습니다!

2024-05-16 11:49 UTC, nogamsung approved these changes

2024-05-16 11:50 UTC, merged